version: 1.0

provider:
  name: openfaas
  gateway: https://${DO_SUBDOMAIN:-antenna}.orionsbelt.ca

configuration:
  copy:
    - ./common

functions:
  slack:
    lang: orions-node12
    handler: ./slack
    image: ${REGISTRY_USER:-orionsbelts}/slack:latest
    readonly_root_filesystem: true
    secrets:
      - slack-client-id
      - slack-client-secret
      - slack-state-secret
