---
name: CI/CD - pull_reqeust

on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

env:
  TF_VAR_do_create_record: true
  TF_VAR_do_domain: ${{ secrets.PROD_DOMAIN }}
  TF_VAR_do_ipv4_float: ${{ secrets.PROD_IPV4 }}
  TF_VAR_do_region: ${{ secrets.PROD_REGION }}
  TF_VAR_do_registry_auth: ${{ secrets.DO_CONTAINER_REGISTRY_AUTH_TOKEN }}
  TF_VAR_do_ssh_key: ${{ secrets.PROD_DO_SSH_KEY_NAME }}
  TF_VAR_do_subdomain: ${{ secrets.PROD_SUBDOMAIN }}
  TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
  TF_VAR_letsencrypt_email: ${{ secrets.PROD_LETSENCRYPT_EMAIL }}
  TF_VAR_letsencrypt_amce: ${{ secrets.PROD_LETSENCRYPT_EMAIL }}
  TF_VAR_ssh_key_file: "${{ secrets.PROD_DO_SSH_KEY_NAME }}.pub"
  TF_VAR_cloud_template: cloud-config-staging.tpl
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  secrets:
    name: Validate Secrets
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Installing dependecies
          brew install python-yq faas-cli
          # Check versions; validate deps
          jq --version
          yq --version

      - name: Run secret validation
        env:
          SECRETS: ${{ toJson(secrets) }}
        working-directory: ./core
        run: scripts/validate-secrets.sh

  terraform:
    name: Validate Terraform
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch Public SSH key
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          SSH_KEY_NAME: ${{ secrets.PROD_DO_SSH_KEY_NAME }}
        working-directory: ./core
        run: scripts/fetch-sshkey.sh

      - name: Fetch Cert PEM File
        working-directory: ./core
        run: scripts/fetch-pem.sh

      - name: Initiate terraform
        working-directory: ./core
        run: terraform init

      - name: Validate terraform
        working-directory: ./core
        run: terraform validate

      # NOTE: This command will validate variables are present/correct
      - name: Plan terraform
        working-directory: ./core
        run: terraform plan

  smoketest:
    name: Smoke Test
    runs-on: ubuntu-20.04
    needs:
      - secrets
      - terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch Public SSH key
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          SSH_KEY_NAME: ${{ secrets.PROD_DO_SSH_KEY_NAME }}
        working-directory: ./core
        run: scripts/fetch-sshkey.sh

      - name: Fetch Cert PEM File
        working-directory: ./core
        run: scripts/fetch-pem.sh

      - name: Initiate terraform
        working-directory: ./core
        run: terraform init

      - name: Apply terraform
        timeout-minutes: 10
        working-directory: ./core
        run: terraform apply -auto-approve

      - name: Wait for System
        working-directory: ./core
        run: scripts/online-check.sh

      - name: Test environment
        if: ${{ success() }}
        run: |
          # Running test commands
          # TODO:
          # - instanciate one secret
          # - instanciate smoketest function
          # - invoke smoketest function
          echo "test"

      - name: Teardown environment
        if: ${{ always() }}
        working-directory: ./core
        run: terraform destroy -auto-approve
