---
name: CI/CD - pull_reqeust

on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

jobs:
  secrets:
    name: Validate Secrets
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Installing dependecies
          brew install python-yq faas-cli
          # Check versions; validate deps
          jq --version
          yq --version

      - name: Run secret validation
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          # Running secret validation script
          cd ${GITHUB_WORKSPACE}/core
          printenv
          bash ./scripts/validate-secrets.sh
