---
name: validations

on: pull_request

jobs:
  secrets:
    name: Validate Secrets
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Installing dependecies
          brew install python-yq faas-cli
          # Check versions; validate deps
          jq --version
          yq --version

      - name: Run secret validation
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          # Running secret validation script
          cd ${GITHUB_WORKSPACE}/core
          bash ./scripts/validate-secrets.sh
